version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.5-stretch-browsers-legacy
    working_directory: /go/src/github.com/lonelyelk/what-build
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: make dep
      - run: make lint
      - run: make test
      - run: make build

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
